import { http } from './http';

const unwrap = (response) => response.data;

export const api = {
  health: () => http.get('/health').then(unwrap),
  getPublicStats: () => http.get('/stats').then(unwrap),
  getCategories: () => http.get('/categories').then(unwrap),
  getRegions: () => http.get('/regions').then(unwrap),
  getProducts: (params = {}) => http.get('/products', { params }).then(unwrap),
  getProduct: (id) => http.get(`/products/${id}`).then(unwrap),
  getCart: () => http.get('/cart').then(unwrap),
  addToCart: (payload) => http.post('/cart', payload).then(unwrap),
  updateCartItem: (itemId, payload) => http.put(`/cart/${itemId}`, payload).then(unwrap),
  removeFromCart: (itemId) => http.delete(`/cart/${itemId}`).then(unwrap),
  clearCart: () => http.delete('/cart').then(unwrap),
  getWishlist: () => http.get('/wishlist').then(unwrap),
  addToWishlist: (payload) => http.post('/wishlist', payload).then(unwrap),
  removeFromWishlist: (productId) => http.delete(`/wishlist/${productId}`).then(unwrap),
  moveWishlistToCart: (payload) => http.post('/wishlist/move-to-cart', payload).then(unwrap),
  getMyOrders: () => http.get('/orders/my').then(unwrap),
  createOrder: (payload) => http.post('/orders', payload).then(unwrap),
  estimateDelivery: (payload) => http.post('/orders/estimate-delivery', payload).then(unwrap),
  updateOrderStatus: (id, status) => http.put(`/orders/${id}/status`, { status }).then(unwrap),
  addCourierReview: (id, payload) => http.post(`/orders/${id}/courier-review`, payload).then(unwrap),
  createPaymentIntent: (payload) => http.post('/payments/create-intent', payload).then(unwrap),
  confirmPayment: (payload) => http.post('/payments/confirm', payload).then(unwrap),
  getReviews: (productId) => http.get(`/reviews/product/${productId}`).then(unwrap),
  getMyReviews: () => http.get('/reviews/my').then(unwrap),
  addReview: (payload) => http.post('/reviews', payload).then(unwrap),
  calculateDelivery: (payload) => http.post('/delivery/calculate', payload).then(unwrap),
  login: (payload) => http.post('/auth/login', payload).then(unwrap),
  register: (payload) => http.post('/auth/register', payload).then(unwrap),
  verifyEmail: (token) => http.get(`/auth/verify-email/${token}`).then(unwrap),
  forgotPassword: (payload) => http.post('/auth/forgot-password', payload).then(unwrap),
  resetPassword: (token, payload) => http.put(`/auth/reset-password/${token}`, payload).then(unwrap),
  me: () => http.get('/auth/me').then(unwrap),
  sellerDashboard: () => http.get('/seller/dashboard').then(unwrap),
  sellerOrders: () => http.get('/seller/orders').then(unwrap),
  sellerReviews: () => http.get('/seller/reviews').then(unwrap),
  sellerProducts: () => http.get('/products/my/products').then(unwrap),
  createSellerProduct: (formData) => http.post('/products', formData).then(unwrap),
  updateProduct: (id, formData) => http.put(`/products/${id}`, formData).then(unwrap),
  deleteProduct: (id) => http.delete(`/products/${id}`).then(unwrap),
  getOrder: (id) => http.get(`/orders/${id}`).then(unwrap),
  updateSellerProfile: (payload) => http.put('/seller/profile', payload).then(unwrap),
  updateAuthProfile: (payload) => http.put('/auth/profile', payload).then(unwrap),
  uploadAvatar: (formData) => http.put('/auth/avatar', formData, { headers: { 'Content-Type': 'multipart/form-data' } }).then(unwrap),
  changePassword: (payload) => http.put('/auth/change-password', payload).then(unwrap),
  getNotifications: (params = {}) => http.get('/notifications', { params }).then(unwrap),
  markNotificationRead: (id) => http.put(`/notifications/${id}/read`).then(unwrap),
  markAllNotificationsRead: () => http.put('/notifications/read-all').then(unwrap),
  courierDashboard: () => http.get('/courier/dashboard').then(unwrap),
  courierOrders: () => http.get('/courier/deliveries').then(unwrap),
  courierAvailableOrders: () => http.get('/courier/available-orders').then(unwrap),
  courierAcceptOrder: (id) => http.post(`/courier/accept-order/${id}`).then(unwrap),
  courierUpdateDeliveryStatus: (id, status) => http.put(`/courier/deliveries/${id}/status`, { status }).then(unwrap),
  updateCourierAvailability: (payload) => http.put('/courier/availability', payload).then(unwrap),
  adminDashboard: () => http.get('/admin/dashboard').then(unwrap),
  adminUsers: () => http.get('/admin/users').then(unwrap),
  adminOrders: () => http.get('/admin/orders').then(unwrap),
  adminPendingProducts: () => http.get('/admin/products/pending').then(unwrap),
  approveProduct: (id, payload) => http.put(`/admin/products/${id}/approve`, payload).then(unwrap),
  markPayout: (id, target) => http.put(`/admin/orders/${id}/payout`, { target }).then(unwrap),
  // Admin category CRUD (full CRUD exists at /admin/categories)
  adminGetCategories: () => http.get('/admin/categories').then(unwrap),
  adminCreateCategory: (payload) => http.post('/admin/categories', payload).then(unwrap),
  adminUpdateCategory: (id, payload) => http.put(`/admin/categories/${id}`, payload).then(unwrap),
  adminDeleteCategory: (id) => http.delete(`/admin/categories/${id}`).then(unwrap),
  // Admin region CRUD (full CRUD exists at /admin/regions)
  adminGetRegions: () => http.get('/admin/regions').then(unwrap),
  adminCreateRegion: (payload) => http.post('/admin/regions', payload).then(unwrap),
  adminUpdateRegion: (id, payload) => http.put(`/admin/regions/${id}`, payload).then(unwrap),
  adminDeleteRegion: (id) => http.delete(`/admin/regions/${id}`).then(unwrap),
  // Admin user status toggle
  adminToggleUserStatus: (id) => http.put(`/admin/users/${id}/status`, {}).then(unwrap),
  getConversations: (params = {}) => http.get('/conversations', { params }).then(unwrap),
  createConversation: (payload) => http.post('/conversations', payload).then(unwrap),
  getMessages: (id) => http.get(`/conversations/${id}/messages`).then(unwrap),
  sendMessage: (id, payload) => http.post(`/conversations/${id}/messages`, payload).then(unwrap),
  markConversationRead: (id) => http.put(`/conversations/${id}/read`).then(unwrap)
};